import Head from 'next/head';
import Image from 'next/image';
import {Section1, Section2, Section3, Section4} from '../Components/Home';
import {Header, Footer} from '../Components/Reusable';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <section>
          <Header />
        </section>
        <section>
          <Section1 />
        </section>
        <section>
          <Section2 />
        </section>
        <section>
          <Section3 />
        </section>
        <section>
          <Section4 />
        </section>
        <section>
          <Footer />
        </section>
      </main>
    </div>
  );
}
